#!/bin/bash -eux

# again, need an instance here

## Create a volume and attach it to the instance
create-and-attach() {
  # create a volume from the snapshot and watch its progress
  ec2-create-volume -z us-east-1b -s 10 | tee create-vol.OUT
  vol=$( awk '{print $2}' create.OUT )
  
  # watch the progress
  while true; do
    ec2-describe-volumes $vol | tee /dev/stderr |
      grep -q creating || break
      sleep 30
  done
  
  ec2-attach-volume $vol -i $instance -d /dev/sdh$1
}

for i in {1..4}; do
  create-and-attach $i
done

