#!/bin/bash -eux

zone=us-east-1b

# create a micro ec2 instance here and put its id into $instance
token=${1:-$(date +%Y-%m-%d-%H-%M)}
echo token is $token
ec2-run-instances ami-08728661 -g default -k testkey -t t1.micro -availability-zone $zone --client-token $token | tee run.OUT
instance=$(awk '/INSTANCE/{print $2}')

while true; do
  ec2-describe-instances | tee describe.OUT
  grep -q pending describe.OUT || break
  sleep 30
done

# now create a volume and attach it to the instance
ec2-create-volume -z $zone -s 50 | tee create-vol.OUT
vol=$( awk '{print $2}' create-vol.OUT )

# watch the progress
while true; do
	ec2-describe-volumes $vol | tee describe-vols.OUT
	grep -q creating describe-vols.OUT || break
	echo === 
	sleep 30
done

# attach it to the instance
ec2-attach-volume $vol -i $instance -d /dev/sdf

# watch the progress
while true; do
        ec2-describe-volumes $vol | tee describe-vols.OUT
	grep -q attaching describe-vols.OUT || break
	echo === 
	sleep 30
done


# snapshot the volume
ec2-create-snapshot $vol | tee create-snap.OUT
snap=$( awk '{print $2}' create-snap.OUT )

# watch the progress
while true; do
	ec2-describe-snapshots $snap | tee describe-snap.OUT
	grep -q creating describe-snap.OUT || break
	echo === 
	sleep 30
done

# create a volume from the snapshot and watch its progress
ec2-create-volume -z $zone -s 50 --snapshot $snap | tee create-vol.OUT
vol=$( awk '{print $2}' create-vol.OUT )

# watch the progress
while true; do
	ec2-describe-volumes $vol | tee describe-vols.OUT
	grep -q creating describe-vols.OUT || break
	echo === 
	sleep 30
done

# attach it to the instance, too
ec2-attach-volume $vol -i $instance -d /dev/sdg

# watch the progress
while true; do
        ec2-describe-volumes $vol | tee describe-vols.OUT
	grep -q attaching describe-vols.OUT || break
	echo === 
	sleep 30
done

snap_and_log.php "Important backup" $vol
ec2-describe-snapshots

ec2_diagram.php
