#!/bin/bash -eux
# illustrate using public data sets

watch-volumes-while() {
  # wait for completion of an event
  condition=$1
  shift
  volumes="$*"

  while true; do
    ec2-describe-volumes $volumes | tee /dev/stderr |
      grep -q $condition || break
    sleep 30
  done
}

# create an instance
zone=us-east-1b

# create a micro ec2 instance here and put its id into $instance
token=${1:-$(date +%Y-%m-%d-%H-%M)}
echo token is $token
ec2-run-instances ami-08728661 -g default -k testkey -t t1.micro -availability-zone $zone --client-token $token | tee run.OUT
instance=$( awk '/INSTANCE/{print $2}' run.OUT )

while true; do
  ec2-describe-instances $instance | tee /dev/stderr |
    grep -q pending || break
  sleep 30
done


snap=snap-753dfc1c  # 7 months of Wikipedia traffic statistics

# create a volume from the snapshot and watch its progress
ec2-create-volume -z us-east-1b -s 320 --snapshot $snap | tee create-vol.OUT
vol=$( awk '{print $2}' create-vol.OUT )

# watch the progress
watch-volumes-while creating $vol

ec2-attach-volume $vol -i $instance -d /dev/sdh

# watch the progress
watch-volumes-while attaching $vol

# now log in to the aws instance so you can mount the volume

key=~/.ssh/testkey.pem	# or whatever yours is called
dnsname=$(ec2-describe-instances $instance | awk '/INSTANCE/{print $4}')

ssh -i $key ec2-user@$dnsname
