#!/bin/bash -eux
# an illustration of how to invoke ec2-run-instances
# to create a running instance from the command line.

source ../../bin/gripe.sh
source ./watchers.sh

ami=ami-2cb05345  # a lamp ami, not EBS-based

token=${1:-$(date +%Y-%m-%d-%H-%M)}
warn token is $token
ec2-run-instances $ami -g default -k testkey -t m1.small -availability-zone us-east-1b --client-token $token | tee run.OUT
instance=$(awk '/INSTANCE/{print $2}' run.OUT)

# track progress
watch-instances-while pending $instance

warn instance is
echo $instance
