#!/bin/bash -eux

# create all three databases
create_domain.php

# add cities and categories
add_category.php Cars Furniture
add_city.php Redmond WA

# add data (calls add_item.php)
insert_sample_data.sh

# look at everything we've put in the database
dump.php


